# ── Build stage: compile native deps (hnswlib, etc.) ──
FROM python:3.11-slim AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

# Install CPU-only PyTorch first, then the rest of the requirements.
# This avoids pulling ~2.5 GB of CUDA libraries that are not needed.
RUN pip install --no-cache-dir \
    torch --extra-index-url https://download.pytorch.org/whl/cpu \
    && pip install --no-cache-dir -r requirements.txt

# Pre-download SBERT model so container starts fast (no HF download at runtime)
RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')"

# Copy data files and indexing script, then regenerate ChromaDB + train predictor
# This ensures the database is built with the installed chromadb version
COPY data/ data/
COPY matcher.py predictor.py index_jobs.py ./
RUN python index_jobs.py

# ── Runtime stage: slim image without build-essential ──
FROM python:3.11-slim

WORKDIR /app

# Copy installed packages and cached model from builder
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY --from=builder /root/.cache/huggingface /root/.cache/huggingface

# Copy freshly-built ChromaDB database from builder (not the stale repo version)
COPY --from=builder /app/chroma_db/ chroma_db/

# Copy trained predictor model from builder (generated by index_jobs.py)
COPY --from=builder /app/predictor_model.pt ./

# Copy application code
COPY main.py matcher.py predictor.py ./
COPY routers/ routers/
COPY services/ services/
COPY data/ data/

EXPOSE 8080

# Railway sets $PORT dynamically; railway.json overrides CMD with $PORT
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
